server:
  port: 7101
  
spring:
  profiles:
    active: dev
   
---

server:
  port: 7101
  
spring:
  profiles: dev
  application:
    name: config-client
    

  
---

server:
  port: 7102 
  
spring:
  profiles: prod
  application:
    name: config-client
    

  

  
   

         
  
   
   
