
  
spring:
  profiles:
    active: dev
   
---

server:
  port: 7101
  
spring:
  profiles: dev
  application:
    name: config-client
    
myparam:
  author: zjf
  date: 2020-03-07
  remark: 测试springcloud bus服务总线2020-03-07 22:09
  
---

server:
  port: 7102 
  
spring:
  profiles: prod
  application:
    name: config-client
    
myparam:
  author: zjf
  date: 2020-03-07
  remark: 测试springcloud bus服务总线
  

  
   

         
  
   
   
