
spring:
  profiles:
    active: dev
  application:
    name: config-client
    
server:
  port: 7001
  
---
spring:
  profiles: test
  application:
    name: config-client
    
server:
  port: 7002
  
---
  
  
spring:
  profiles: prod
  application:
    name: config-client
    
server:
  port: 7003
  

  
   

         
  
   
   
